"""
TreatmentFlow
Constraint Optimization: Hospital Bed Assignment - Greedy Approach

By Adam Neto and Emese Elkind
Started: February 2025

CISC 352: Artificial Intelligence
"""

from HospitalClasses import HospitalRecords
from HospitalClasses import Scheduler

from ortools.init.python import init
from ortools.linear_solver import pywraplp

# This file is an experimental application of our bed assignment system using the greedy paradigm

"""
Information we are working with:
- list of patients
    - includes arrival time 
    - includes patient priority (generated by DL file)

Goal of solution:
- optimize bed assignment based on priority and arrival
    - minimize the wait times of patients, with higher-priority patients scaled such 
        that their wait times are more punishing if long (multiply wait times by patient cost)

Summary of approach:
- sort list of patients by arrival time (OR create running list that trickles in by arrival time?)
    - sort patients with identical arrival times by priority
        - assign highest priority patients to beds with greedy methods, such that next available bed
            is assigned to next highest priority patient
            - will need a running list of patients to-be-served
                - if a new patient arrives after current patients with a higher priority,
                    they will be assigned a bed first
                        POTENTIAL ISSUE: how to avoid low-priority starvation
"""

# running hospital simulation without constraint satisfacation
B = 10  # CHANGE VALUE TO CHANGE NUMBER OF BEDS
P = 75  # CHANGE VALUE TO CHANGE NUMBER OF PATIENTS

records = HospitalRecords(B)
records.gen_patient_list(P)

print("\nPATIENTS:")
for patient in records.patient_list:
    print(f"{patient.id}, {patient.priority}, {patient.arrival_time_printed()}, --- {patient.service_time_printed()}")

print("\nUNSERVED:")
for patient in records.unserved:
    print(f"{patient.id}, {patient.priority}, {patient.arrival_time_printed()}, --- {patient.service_time_printed()}")

# NON-TIME BOUNDED SERVING OF PATIENTS
# print("SERVING PATIENTS")
# records.serve_patients()
# for bed in records.beds:
#     print(f"Bed{bed.id}: {bed.occupant.id}, {bed.occupant.priority}, {bed.occupant.arrival_time_printed()}, --- {bed.occupant.service_time_printed()}")
# print("UNSERVED:")
# for patient in records.unserved:
#     print(f"{patient.id}, {patient.priority}, {patient.arrival_time_printed()}, --- {patient.service_time_printed()}")

# running the hospital simulation
scheduler = Scheduler(records)
scheduler.run_hospital()
scheduler.waiting_times()

                
"""
Now that problem formulation is complete, we can calculate constraints and solutions given an objective function

Proposed objective function: 
    - minimize the wait times for each patient, making where high-priority patients wait times are minimized the most
        - medium-priority wait times are minimized second, etc.

Proposed constraints:
    - cannot assign a patient to an occupied bed
    - cannot assign a lower priority patient when a higher priority patient is waiting
    - must assign (or queue) every patient in the list of patients
"""

# create solver
# solver = pywraplp.Solver.CreateSolver("GLOP")
# if not solver:
#     raise Exception("Could not create solver GLOP")

# bed assignment constraints
"""
Patient contiguousness
-   a patent being assigned to a bed will be assigned for a congiguous period

Patient tenure
-   the difference between the final minute where a patient is assigned and the first
    cannot exceed the patient's service time
    -   for every minute where a patient is assigned to a bed (where value is true),
        the variable in the same bed (service_time) minutes ago is not the same patient (or no patient)
-   the difference between the final minute where a patient is assigned and the first
    MUST equal the patient's service time, unless:
    -   (final minute of day - first minute of patient assignment) < service time

Patient to bed exclusivity
-   a patient can only be assigned a bed when there is no other patient in it

Patient arrival time consideration
-   a patient can only be assigned a bed when they have already arrived at the hospital
"""

